lockfileIncludeTarballUrl: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@softarc/*"
  - "@angular/*"
  - "@angular-devkit/*"
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: false
  msw: true
  nx: false
