/**
 * Source of the dev-only SSR bootstrap injected into the `ng serve` server
 * bundle (see `plugin/dev-host-instances-plugin.ts`).
 *
 * Under `ng serve` the host loads via Vite's SSR runner while remotes load via
 * the orchestrator's Node loader — two `@angular/core` instances → NG0203. Fix:
 * `hostInstances` publishes the host's singletons for remotes to re-use. We pass
 * our own `load` so instances are captured in the host's realm, not the
 * orchestrator's (they differ under Vite SSR). Prod dedupes via the import map.
 */
export interface DevHostInstancesOptions {
  /** Browser output dir relative to the workspace root, e.g. `dist/host/browser`. */
  relBrowserPath: string;
  /**
   * Origin of the dev server, e.g. `http://localhost:4200`. Under `ng serve` the
   * manifest lives only in Vite's memory, so it's fetched over HTTP from here.
   * Omit for non-serve builds, where it's read from `relBrowserPath` on disk.
   */
  devServerOrigin?: string;
}

export function generateDevHostInstancesEntry({
  relBrowserPath,
  devServerOrigin,
}: DevHostInstancesOptions): string {
  // relBrowserPath is resolved against process.cwd() (the workspace root under
  // `ng serve`), where the federation build writes its artifacts.
  return `// Generated by @angular-architects/native-federation-v4 (dev SSR) — do not edit.
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const browserDir = join(process.cwd(), ${JSON.stringify(relBrowserPath)});
const manifestPath = join(browserDir, 'federation.manifest.json');
const devServerOrigin = ${JSON.stringify(devServerOrigin ?? null)};

// Vite serves the manifest and remote entries from memory under \`ng serve\`,
// so prefer the dev server's origin over the never-present on-disk path.
const hostRemoteEntry = devServerOrigin
  ? devServerOrigin + '/remoteEntry.json'
  : join(browserDir, 'remoteEntry.json');

// A static host returns 404 for the manifest — fetch it here so that 404
// degrades to an empty manifest (which still bridges host singletons) instead
// of failing init. With no known origin, fall back to the on-disk path.
async function resolveManifest() {
  if (devServerOrigin) {
    try {
      const res = await fetch(devServerOrigin + '/federation.manifest.json');
      if (res.ok) return await res.json();
      return {};
    } catch {
      // Origin unreachable — fall through to the on-disk path.
    }
  }
  return existsSync(manifestPath) ? manifestPath : {};
}

const g = globalThis;

if (!g['__NF_HOST_SERVER_LOADER__']) {
  const { initNodeFederation } = await import('@softarc/native-federation-orchestrator/node');

  let loadRemoteModule;
  let initError;
  try {
    ({ loadRemoteModule } = await initNodeFederation(
      await resolveManifest(),
      {
        hostRemoteEntry,
        // load through THIS module's graph so we capture the host's instances,
        // not the orchestrator realm's (which differs under Vite SSR).
        hostInstances: { load: (s) => import(/* @vite-ignore */ s) },
      },
    ));
  } catch (err) {
    initError = err;
  }

  // Published iff the bridge actually ran. If not, fail fast — a missing bridge
  // surfaces as an intermittent, hard-to-trace NG0203 instead.
  const published = g['__NF_HOST_INSTANCES__'];
  const bridged = published && Object.keys(published).length > 0;
  if (!bridged) {
    throw new Error(
      '[native-federation] dev SSR host-instance bridge did not engage — ' +
      'globalThis.__NF_HOST_INSTANCES__ was not published. Usually ' +
      "'@softarc/native-federation-orchestrator/node' was bundled by Vite " +
      'instead of externalized (so its module.register() loader never ran), ' +
      'or the installed orchestrator predates the hostInstances bridge.' +
      (initError ? ' Cause: ' + (initError && initError.message || initError) : ''),
    );
  }

  // Bridge ran but init failed (e.g. a remote is down): render without remotes.
  if (initError) {
    console.warn(
      '[native-federation] dev SSR: federation init failed; rendering host without remotes:',
      initError && initError.message || initError,
    );
  } else {
    g['__NF_HOST_SERVER_LOADER__'] = loadRemoteModule;
  }
}
`;
}
