/**
 * Source of the Angular-free SSR entry the build emits as
 * `dist/<app>/server/server.mjs`.
 *
 * The CLI prepends the `@angular/ssr` registration to its emitted entry, so the
 * entry's *static* graph pulls in `@angular/*` — which ESM evaluates before the
 * body runs, i.e. before `initNodeFederation()` could register the node loader.
 * Result: two `@angular/core` instances (NG0203 / `JIT compilation failed`).
 *
 * Fix: the build renames the CLI's entry to `bootstrap-server.mjs` and writes
 * this Angular-free entry as `server.mjs`. It registers the loader first, then
 * dynamically imports the bootstrap — so every `@angular/*` resolves to the one
 * shared federated chunk.
 */
export const federationServerEntry = `// Generated by @angular-architects/native-federation-v4 — do not edit.
// Angular-free entry: registers the federation node loader BEFORE any
// '@angular/*' module is evaluated, then hands off to the real server bundle.
import { initNodeFederation } from '@softarc/native-federation-orchestrator/node';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const serverDir = dirname(fileURLToPath(import.meta.url));
const browserDir = join(serverDir, '../browser');

// Static hosts have no manifest; an empty one still registers the host's shared
// externals via 'hostRemoteEntry', which is what dedupes '@angular/*'.
const manifestPath = join(browserDir, 'federation.manifest.json');
const hostRemoteEntry = pathToFileURL(join(browserDir, 'remoteEntry.json')).href;

try {
  const { loadRemoteModule } = await initNodeFederation(
    existsSync(manifestPath) ? manifestPath : {},
    {
      hostRemoteEntry,
      // Bridge the host's shared singletons (every '@angular/*' secondary, rxjs,
      // zone.js, …) to remotes loaded during SSR. The loader is registered above
      // before any '@angular/*' is evaluated, so the default '(s) => import(s)'
      // resolves each specifier through the import map — the one shared chunk —
      // and publishes it on globalThis.__NF_HOST_INSTANCES__. Without this the
      // remote's '@angular/core/rxjs-interop' resolves a private build-internal
      // chunk instead of the shared core instance → NG0203 (no injection context).
      hostInstances: 'all',
    },
  );
  // Bridge the loader to the app (read by the host's SSR render code).
  globalThis['__NF_HOST_SERVER_LOADER__'] = loadRemoteModule;
} catch (err) {
  console.warn(
    '[native-federation] initNodeFederation failed; SSR will render without federated remotes:',
    (err && err.message) || err,
  );
}

// The bundle only listens when it's the main module or pm_id is set; it's now
// imported (not main), so opt it into listening.
process.env['pm_id'] ??= '1';

await import('./bootstrap-server.mjs');
`;
